#:schema node_modules/wrangler/config-schema.json
name = "noir"
main = "src/index.js"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[triggers]
crons = ["30 3 * * *"]  # This will run after every 3 hours 30 minutes

[vars]
REALM_ID = "65a64dbe10aba26bd067fa9d"
REALM_KEY = "example_user"